-- AlterTable
ALTER TABLE `User` MODIFY `status` ENUM('SIN_DOCUMENTOS', 'DOCUMENTOS_INCOMPLETOS', 'PENDIENTE_REVISAR', 'EN_REVISION', 'OBSERVADO', 'RETENIDO_USE', 'PREPARACION', 'ENVIADO_SPONSOR', 'OBSERVADO_SPONSOR', 'RECHAZADO_SPONSOR', 'APROBADO_SPONSOR', 'DS2019_EMITIDO', 'RETIRADO', 'ACTIVO') NOT NULL DEFAULT 'ACTIVO';
