-- Agrega el valor INACTIVO al enum user_status en todas las columnas que lo usan
ALTER TABLE `User` MODIFY COLUMN `status` ENUM('SIN_DOCUMENTOS','DOCUMENTOS_INCOMPLETOS','PENDIENTE_REVISAR','EN_REVISION','OBSERVADO','RETENIDO_USE','PREPARACION','ENVIADO_SPONSOR','OBSERVADO_SPONSOR','RECHAZADO_SPONSOR','APROBADO_SPONSOR','DS2019_EMITIDO','RETIRADO','ACTIVO','INACTIVO') NOT NULL DEFAULT 'ACTIVO';

ALTER TABLE `UserHistoryStatus` MODIFY COLUMN `status` ENUM('SIN_DOCUMENTOS','DOCUMENTOS_INCOMPLETOS','PENDIENTE_REVISAR','EN_REVISION','OBSERVADO','RETENIDO_USE','PREPARACION','ENVIADO_SPONSOR','OBSERVADO_SPONSOR','RECHAZADO_SPONSOR','APROBADO_SPONSOR','DS2019_EMITIDO','RETIRADO','ACTIVO','INACTIVO') NOT NULL;
